### ISSUE TITLE
--paper-input-container-focus-color should not be set

### ISSUE THREAD

**Issue by kito99** [ellipticaljs/paper-autocomplete#51]
Currently, paper-autocomplete sets --paper-input-container-focus-color to a specific value:

```css
      --paper-input-container-focus-color: #2196f3;
```

This value shouldn't be hardcoded, because it's set to `var(--primary-color)` by default. As a result, paper-autocomplete won't match other paper-input derived fields on the same page.

This is easy to work-around by adding some CSS in the parent element:

```css
			paper-autocomplete {
				--paper-input-container-focus-color: var(--primary-color);
			}
```

However, I don't see why the value should be hardcoded in the first place.
