### ISSUE TITLE
Leaking CSS styles

### ISSUE THREAD

**Issue by alejost848** [ellipticaljs/paper-autocomplete#68]
I had been experiencing a problem in a project I'm working on, where a `paper-item` was having an unexpected color change on hover. Unexpectedly, I traced back the problem to this CSS rule from `paper-autocomplete-suggestions`:
```css
paper-item:hover,
:host ::content paper-item:hover {
  background: #eee;
  color: #333;
  cursor: pointer;
}
```
After looking for a solution online, I found [this article](https://medium.com/collaborne-engineering/leaking-css-styles-in-polymer-ae8d9cf9b775) where they traced down the problem to how they had stored the <style> tag in one of their elements:

```html
<dom-module>
  <style></style>
  <template></template>
</dom-module>
```

It turns out that styles should be declared inside the template tag in an element. So, by simply placing the `<style>` tag within the `<template>` tag solved the problem:

```html
<dom-module>  
  <template>
    <style></style>
  </template>
</dom-module>
```
